### ISSUE TITLE
Update stress scoring on ways

### ISSUE THREAD

**Issue by spencerrecneps** [azavea/pfb-network-connectivity#220]
This is mostly just a heads up that I'll be making some modifications to the scoring of ways. We've been waiting for comments on our methodology from an academic who has done similar work. We finally got his comments last week so I'll be making some tweaks.

This should only affect code internal to the SQL scripts so it shouldn't have an impact on the larger tool.

**Comment by CloudNiner** [comment]
Ok. Note that we will be bringing up a production stack in preparation for the first batch run of cities on April 10, so any changes will need to be fully tested on the staging stack before that date. We're making a few more minor modifications to the staging stack and plan on sending you a login by Wednesday March 29 so that you can run test jobs on staging to verify analysis correctness.

Let us know if this timeline needs adjustment for any reason!

**Comment by spencerrecneps** [comment]
Good to know. I'm aiming to have all SQL routines in a final state by the end of this week.

**Comment by CloudNiner** [comment]
Does #222 address the remaining work you were planning to do on this issue, or are there more changes coming?

**Comment by spencerrecneps** [comment]
More changes coming, but these should not impact any external processes. It's just tweaking the scoring here and there.

**Comment by CloudNiner** [comment]
Followup Azavea tasks for this:
- [ ] Review #222 
- [ ] ensure overall_scores still saves properly back to the main DB
- [ ] Include additional destinations in export_connectivity
- [ ] Export destinations as shp as well as geojson
  - [ ] Add shp urls to AnalysisJob.destination_urls

**Comment by CloudNiner** [comment]
Ok, thanks. We'd be mostly concerned with any schema changes to any of the tables we're exporting for download/searching/filtering/sorting so if that's pretty much set after #222 then we'll continue forward.

**Comment by spencerrecneps** [comment]
Yep. I think we're done with schema changes now.

**Comment by spencerrecneps** [comment]
Closed by https://github.com/azavea/pfb-network-connectivity/pull/241
