### ISSUE TITLE
Add sorting options to AnalysisJob API endpoint

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#242]
- [ ] Last updated (job completion datetime)
- [ ] Highest Rated
- [ ] Lowest Rated
- [ ] Alphabetical

**Comment by flibbertigibbet** [comment]
After discussion, sort by job start time instead of completion (`created_at` already in `ordering_fields`).

Alphabetical sort is by neighborhood name.

**Comment by KlaasH** [comment]
I changed the title because I think AnalysisJob was a typo--though most of the data points come from analysis jobs, the purpose of this is to be able to sort the neighborhoods list, so we need to be sorting by latest job.

Which I guess means latest completed job, since it wouldn't be good for a neighborhood to lose its rankings when a new job is kicked off.  So in that case completion datetime of the latest job does make sense for sorting.

**Comment by CloudNiner** [comment]
Maybe as an addendum we need to have a short chat about how we could better construct API calls that provide the information the views need in a straightforward manner, and update these issues or add a new one.

**Comment by KlaasH** [comment]
Just kidding, the AnalysisJob is the right answer.  We want to get the latest job per neighborhood and get at neighborhood information (name, overall score) through that.
