### ISSUE TITLE
API endpoints very slow on production

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#373]
With a large number (211) of neighborhoods:
![screen shot 2017-05-01 at 08 10 27](https://cloud.githubusercontent.com/assets/1818302/25579411/c9b222f0-2e45-11e7-9eeb-20866abd4ad9.png)

**Comment by CloudNiner** [comment]
The requests after the first three are all to load the neighborhood geojsons. We could potentially generate those once when the neighborhood is loaded and store the geojson on S3 instead of generating it with each request.

**Comment by flibbertigibbet** [comment]
The request for just the neighborhood points took nearly nine seconds, which is concerning, especially since that gets pulled on the home page as well.

Regarding the bounds GeoJSON queries, it might be a good idea to reduce the pagination size for the neighborhoods (currently at the default of 20). Most of the cards for those won't be visible without scrolling.

**Comment by CloudNiner** [comment]
If this takes more time than allotted, create new issues as followup tasks.

**Comment by CloudNiner** [comment]
After deployment this morning, the `/api/analysis_jobs` and `/api/neighborhoods_geojson` are still very slow (~9s) for each request:

![screen shot 2017-05-08 at 09 06 44](https://cloud.githubusercontent.com/assets/1818302/25805551/1df4496e-33ce-11e7-895b-0c806e354e2f.png)

**Comment by flibbertigibbet** [comment]
Directly accessing `/api/neighborhoods_geojson/?format=json` on production, it loads in <100ms. The issue appears to rather be with the `analysis_jobs` endpoint, which is also slow when accessed directly.

**Comment by flibbertigibbet** [comment]
Issue specifically seems to be filtering and ordering analysis jobs by status; created #400 for that.
