### ISSUE TITLE
Text changes to public site

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#380]
https://docs.google.com/a/azavea.com/document/d/1NNj8k7D8ySqROuCA2QQkWZfb4HB9zxjzVlsDISr4P6E/edit?usp=sharing

**Comment by flibbertigibbet** [comment]
1-4 look to be straightforward text changes. Some questions and comments on the last two items:

5 (sort by population) will be non-trivial, and require implementing sort on the JSON object of associated results via the `AnalysisJob` endpoint to get at the population count. Also, should the population be displayed in the UI somewhere?

Regarding the first part of 6 (last updated date), currently this displays slightly above where requested, below the city name.
![image](https://cloud.githubusercontent.com/assets/960264/25672660/996f6788-3002-11e7-8e61-1838ad276d34.png)

Is the request to move this from where it is now?

Regarding the second part of 6, this also looks to be non-trivial. Do we know what this 'print' functionality is supposed to do?

**Comment by jcahail** [comment]
Re: sort by population - #300 added population totals to neighborhood_overall_scores tables and set limits on population categories. When this sort by option is chosen, the three headers should simply read "Large", "Medium", and "Small"

Current position of Last Updated Date is fine--please ignore request for change.

Re: print functionality, I have to defer to @CloudNiner --he and Matt discussed it quite a bit.

**Comment by flibbertigibbet** [comment]
Regarding population: right, it's in the results JSON, but the way that is stored means that object is not directly accessible in a Django model for a normal sort, which is why it will require non-trivial effort to get at it to implement sorting by population in the UI.

Commenting here to point out that 5 and 6 can be broken out to separate tasks, and are more substantive than text changes. 1-4 are trivial text changes we can cover in a single issue.

**Comment by flibbertigibbet** [comment]
Created #395 and #396 for items 5 and 6 from the document, respectively. This issue is for the text changes in 1-4.
