### ISSUE TITLE
Add middle OrgAdmin user level

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#389]
Currently we support two user levels:
- Administrator: RW on all models
- Viewer: R on AnalysisJob/Neighborhood

We need to add a third user level, to provide to PFB so they can create their own users. This OrgAdmin level should have the following permissions:
- R on AnalysisJob/Neighborhood
- RW on Users in the OrgAdmin's organization, but can only create users with an equal or lower permission level (so only create OrgAdmins or Viewers)

Ensure that the existing Administrator/Viewer roles work as expected as part of this task.

**Comment by flibbertigibbet** [comment]
Currently the app has four user roles and two organizations. The organizations were modified in #60 to serve the purpose of user roles for access permissions; now there is both an `admin` user role and an `admin` organization. In current usage, user roles are effectively unused and could be replaced entirely by the organization permissions.

It is unclear if the intent of this issue is to create a third "organization" for user-level access permissions, or to implement a user role.
