### ISSUE TITLE
Filtering and ordering of analysis jobs slow in API

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/pfb-network-connectivity#400]
On production, querying `/api/analysis_jobs/?format=json&latest=True&limit=8&ordering=-overall_score&status=COMPLETE` takes over 9 seconds, but querying `/api/analysis_jobs/?format=json&limit=8` takes only ~350ms.

Fixing the slow filtering and ordering of analysis jobs should address #373.

**Comment by flibbertigibbet** [comment]
To [be specific](https://github.com/azavea/pfb-network-connectivity/blob/develop/src/django/pfb_analysis/filters.py#L36), hitting `/api/analysis_jobs/?format=json&latest=True&limit=8&ordering=-overall_score&status=COMPLETE` runs 25 separate queries, some with sub-queries.

**Comment by CloudNiner** [comment]
Not ideal. @KlaasH and I briefly discussed this in passing, and it's likely that the quickest solution here is to denormalize a bit, so that analysis job stores its latest status as a db field, and neighborhood stores the latest analysis as a foreign key ref. It should be relatively straightforward to keep these properties up to date.

**Comment by flibbertigibbet** [comment]
Filtered analysis job queries on production gone from 9+ seconds to ~200ms.
