### ISSUE TITLE
Austin issue

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#452]
Austin shows up twice, with the same odd boundary.
![image](https://cloud.githubusercontent.com/assets/24727081/26110550/b02e781a-3a20-11e7-9916-566bcf2c6dfd.png)

Is this a map issue or a boundary shapefile issue?

**Comment by CloudNiner** [comment]
Duplicate neighborhood fixed as part of #453 

As for the odd boundary, the answer is...its complicated.

The Austin, TX MultiPolygon contains two polygons, one of which is very small and disjoint:
![screen shot 2017-05-17 at 15 45 56](https://cloud.githubusercontent.com/assets/1818302/26172920/0b34bb78-3b18-11e7-8163-26502a6d79c5.png)

When calling simplify without preserving topology, in all cases we currently handle in our simplification method, the result is a simplification of the small polygon shown above, rather than the larger actual boundary. 

I manually ran the following on production to fix the badly simplified geometry:
```
n = Neighborhood.objects.get(name='austin-tx')
n.geom_simple =  n.geom.simplify(SIMPLIFICATION_TOLERANCE_MORE, preserve_topology=True)
n.save()
```
This resulted in a MultiPolygon with ~1100 points, down from ~9000 in the original geom, and is a manageable, but not ideal size for now.

I spoke with @KlaasH and we have a few concerns about making modifications to the existing `pfb_analysis.models.simplify_geom`, we should followup with @flibbertigibbet when she returns, we don't want to make major changes to this method because we could easily mess up more simplified geometries than we fix. We think that updating the method to use `preserve_topology` will always work, but we worry about making the simplified geometries generally larger than they need to be.

In any case, here's the updated simplified geom on the site:
![screen shot 2017-05-17 at 15 54 30](https://cloud.githubusercontent.com/assets/1818302/26173248/2ae323e6-3b19-11e7-82ab-94defbcdf86b.png)
![screen shot 2017-05-17 at 15 54 37](https://cloud.githubusercontent.com/assets/1818302/26173247/2adf09e6-3b19-11e7-9a41-3b5ef671e838.png)

**Comment by KlaasH** [comment]
Ann Arbor has this problem as well:
![image](https://cloud.githubusercontent.com/assets/6598836/26261142/10fc1d62-3c9e-11e7-8917-b48084877aad.png)

Possibly we should run a query to find all geometries with fewer than some minimum number of points.

Or if we re-process all the geometries when we do the actual fix for this, that would work, too.  Though it might still be worth double-checking.

**Comment by CloudNiner** [comment]
Ok, so 15 neighborhoods have less than 10 points (and 40 neighborhoods have less than 20 points):
```
>>> from django.contrib.gis.db.models.functions import NumPoints
>>> for n in Neighborhood.objects.annotate(num_points=NumPoints('geom_simple')).filter(num_points__lt=10):
...     print n.label
...
Gateway, Portland, OR
Phoenix, AZ
Baltimore, MD
Champaign, IL
Springfield, IL
Baton Rouge, LA
Beaverton, OR
Ann Arbor, MI
Denver, CO
Fayetteville, AR
Springdale, AR
West Chester, PA
Livonia, MI
Pittsford, NY
Pelham Manor, NY
```

Some of these are legit, like (surprisingly) Baltimore, MD or the Gateway neighborhood in Portland, OR. Most, however, are not.

It seems safe to temporarily run the same logic as above:
```
n = Neighborhood.objects.get(name='some-neighborhood')
n.geom_simple =  n.geom.simplify(SIMPLIFICATION_TOLERANCE_MORE, preserve_topology=True)
n.save()
```
for each of the neighborhoods with a low number of points. If they naturally have a low number of points (Baltimore, etc) than that's fine, since we aren't gaining anything anyways. Otherwise, this should fix the simplified geoms up if they were complicated but aren't simplifying correctly via our previous logic.

Thoughts?

**Comment by CloudNiner** [comment]
@klaash thoughts?

**Comment by KlaasH** [comment]
Yeah, that looks great.  Very clear distinction, and it confirms that point counting is not a good strategy because some geometries are just actually simple.

Still planning to do those fixes as a one-off then come back to it, or would a check like this go into the new-boundary saving code now?

**Comment by CloudNiner** [comment]
I think a one-off and then come back to cleaning up the boundary saving code as a separate issue, which I'll create before closing this one. While the code fix is pretty quick, it's not completely trivial, and it may still make sense to just always use `preserve_topology`.

**Comment by CloudNiner** [comment]
I ran the following one-off code in the production console:
```python
from django.contrib.gis.db.models.functions import Area
from pfb_analysis.models import SIMPLIFICATION_TOLERANCE_MORE
for n in Neighborhood.objects.annotate(geom_area=Area('geom'), geom_simple_area=Area('geom_simple')).annotate(area_p=(F('geom_simple_area') / F('geom_area'))).order_by('area_p')[:12]:
    n.geom_simple =  n.geom.simplify(SIMPLIFICATION_TOLERANCE_MORE, preserve_topology=True)
    n.save()
```

'Brielle NJ' is now the neighborhood with the lowest area ratio, at 0.97.

Also created #488 to address the simplify_geom method issues later.
