### ISSUE TITLE
Update ECS launch config AMI to resolve clock skew

### ISSUE THREAD

**Issue by rbreslow** [azavea/pfb-network-connectivity#579]
This is in response to a behavior where a clock skew on an EC2 instance can prevent new ECS tasks from starting.

I investigated the viability of using a [cloud-init module](http://cloudinit.readthedocs.io/en/latest/topics/modules.html#ntp) to configure the [Amazon Time Sync service](https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/): azavea/terraform-aws-ecs-cluster#25

I found that the [latest](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html) Amazon Linux AMI `amzn-ami-2018.03.a-amazon-ecs-optimized (ami-5253c32d)` already has legacy NTP configured to use the new service:

```bash
# Use and prefer the Amazon Time Service server
server 169.254.169.123 prefer iburst minpoll 3
```

To see if the configuration above was present in our EC2 container instances, I ran a diff between `ntp.conf` from the AMI we're currently running `amzn-ami-2016.09.f-amazon-ecs-optimized (ami-b2df2ca4)` and the latest Amazon Linux AMI:

```diff
diff --git a/ntp_old.conf b/ntp.conf
index 2ee2fbb..37a50fa 100644
--- a/ntp_old.conf
+++ b/ntp.conf
@@ -1,11 +1,14 @@
-# For more information about this file, see the man pages
-# ntp.conf(5), ntp_acc(5), ntp_auth(5), ntp_clock(5), ntp_misc(5), ntp_mon(5).
+# For more information about this file, see the ntp.conf(5) man page.

+# Record the frequency of the system clock.
 driftfile /var/lib/ntp/drift

 # Permit time synchronization with our time source, but do not
 # permit the source to query or modify the service on this system.
-restrict default nomodify notrap nopeer noquery
+restrict default nomodify notrap nopeer noepeer noquery
+
+# Permit association with pool servers.
+restrict source nomodify notrap noepeer noquery

 # Permit all access over the loopback interface.  This could
 # be tightened as well, but to do so would effect some of
@@ -16,19 +19,15 @@ restrict ::1
 # Hosts on local network are less restricted.
 #restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap

+# Use and prefer the Amazon Time Service server
+server 169.254.169.123 prefer iburst minpoll 3
+
 # Use public servers from the pool.ntp.org project.
 # Please consider joining the pool (http://www.pool.ntp.org/join.html).
-server 0.amazon.pool.ntp.org iburst
-server 1.amazon.pool.ntp.org iburst
-server 2.amazon.pool.ntp.org iburst
-server 3.amazon.pool.ntp.org iburst
-
-#broadcast 192.168.1.255 autokey    # broadcast server
-#broadcastclient            # broadcast client
-#broadcast 224.0.1.1 autokey        # multicast server
-#multicastclient 224.0.1.1        # multicast client
-#manycastserver 239.255.254.254        # manycast server
-#manycastclient 239.255.254.254 autokey # manycast client
+pool 2.amazon.pool.ntp.org iburst
+
+# Reduce the maximum number of servers used from the pool.
+tos maxclock 5

 # Enable public key cryptography.
 #crypto
```

We should evaluate updating the ECS launch config AMI, possibly changing the value of `var.ecs_instance_ami_id` to `ami-5253c32d`. 

It's worth noting that when ECS with Amazon Linux 2 goes GA, `chronyd` will be the default NTP daemon and will be preconfigured to use the Amazon Time Sync service.

**Comment by CloudNiner** [comment]
#584 was caused by the time sync service being out of sync again. There's also a note in the comments over there about the Docker daemon having crashed on one of the web workers. Just noting it here to keep track of downstream issues caused by this.

**Comment by KlaasH** [comment]
> It's worth noting that when ECS with Amazon Linux 2 goes GA, chronyd will be the default NTP daemon and will be preconfigured to use the Amazon Time Sync service.

This has happened, so it seems like we should be able to get our worker instances running `chrony` just by upgrading the AMI in the `tfvars`.  As of right now, per [the page Rocky linked](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html), I believe the AMI we'd want is `amzn2-ami-ecs-hvm-2.0.20190709-x86_64-ebs` aka `ami-0dca97e7cde7be3d5`.

**Comment by KlaasH** [comment]
I updated `ecs_instance_ami_id` in the staging `.tfvars` file and triggered a build/deploy in Jenkins.

The AMI ID I quoted above wasn't quite right--it was the `us-east-2` one, and these resources are in `us-east-1`.  So the correct one has the same AMI name but a different ID, `ami-0fac5486e4cff37f4`.

The [build and deployment](http://urbanappsci.internal.azavea.com/job/azavea/job/pfb-network-connectivity/job/develop/338/) went fine.  Here's the relevant bit of the `plan` output:
![image](https://user-images.githubusercontent.com/6598836/62880580-bb7f3500-bcfb-11e9-8c84-e329407190cb.png)

Once everything was up, I logged into the instance and confirmed that `chrony` was running:
```
[root@ip-10-0-3-215 ec2-user]# chronyc tracking
Reference ID    : A9FEA97B (169.254.169.123)
Stratum         : 4
Ref time (UTC)  : Mon Aug 12 16:13:39 2019
System time     : 0.000003077 seconds fast of NTP time
Last offset     : +0.000001465 seconds
RMS offset      : 0.000002762 seconds
Frequency       : 30.284 ppm fast
Residual freq   : +0.001 ppm
Skew            : 0.043 ppm
Root delay      : 0.000579693 seconds
Root dispersion : 0.000089199 seconds
Update interval : 16.3 seconds
Leap status     : Normal
```

The staging site had been shut down, since it was a while since we last worked on this, so this deploy didn't show what happens when a new launch configuration is deployed while instances from an old launch configuration are running.  But I believe we've experienced that before and the answer was "not much".  That is, the new launch configuration will be there for new instances, but the old instances won't be automatically swapped out.

So after we've done a deployment with this new AMI setting, I believe we'll need to cycle out the instances manually, by bringing new ones up then removing the old ones from the pool and shutting them down.  If we want to do a dry run of that process on staging, to map out the steps and confirm that we know how to do it while maintaining service availability, we would also want to set `pfb_app_https_ecs_deployment_min_percent` in the staging tfvars to "100" to make it a realistic simulation of the production environment.

**Comment by rbreslow** [comment]
>So after we've done a deployment with this new AMI setting, I believe we'll need to cycle out the instances manually, by bringing new ones up then removing the old ones from the pool and shutting them down. 

From experience, I would be comfortable running these steps in production:

- [ ] Double desired capacity of the ASG
- [ ] Mark old container instances as draining
- [ ] Wait for ECS tasks to move to new container instances
- [ ] Restore original desired capacity of the ASG
