### ISSUE TITLE
Load analysis geometries into AnalysisJob model

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#587]
This task is required to support admin user uploaded analysis results.

- [ ] Add appropriate geom fields to the AnalysisJob model
- [ ] Write migration that iterates existing AnalysisJobs and loads the geometries from the shapefile urls we've already stored

Consider that in follow up tasks we'll need to perform the same shapefile -> geom field task when we load in uploaded user jobs.

**Comment by flibbertigibbet** [comment]
From conversation with @CloudNiner, the two results shapefiles to load for this task are the two available for download from the map UI, Census blocks and neighborhood ways.

From conversation in channel, the purpose is to support presentation via Tilegarden (#591) rather than with pre-generated tiles.
