### ISSUE TITLE
Store and pass city FIPS for neighborhood

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/pfb-network-connectivity#608]
Store added `PFB_CITY_FIPS` value added in #585 on the `Neighborhood` model, and pass it to analysis runs via environment variable, as the state FIPS is passed [here](https://github.com/azavea/pfb-network-connectivity/blob/0.7.0/src/django/pfb_analysis/models.py#L651).

Depends on #585.

**Comment by KlaasH** [comment]
To fully integrate this, there are some further pieces:
- Add it to the neighborhood import [here](https://github.com/azavea/pfb-network-connectivity/blob/0.8.0/src/django/pfb_analysis/models.py#L347-L354), since most neighborhoods are added via batch shapefile.
- For development, add it into the [command printed to the logs](https://github.com/azavea/pfb-network-connectivity/blob/0.8.0/src/django/pfb_analysis/models.py#L700).
- Add a field in the "Create neighborhood" view--similar to PR #656, but hopefully simpler since it would just be an integer field, not a menu selection.

There may be others as well, and the ones above might touch more points in the code than the ones referenced.
