### ISSUE TITLE
django-q container missing from update and build scripts

### ISSUE THREAD

**Issue by KlaasH** [azavea/pfb-network-connectivity#616]
I noticed while testing PR #615 that the django-q container was crashing because it couldn't find `django_countries`.  Turns out all it needed was a `docker-compose build`, but that hadn't happened because it's not in the list of containers to build in [`scripts/update`](https://github.com/azavea/pfb-network-connectivity/blob/0.7.0/scripts/update).  It's also missing from `cibuild` and `cipublish`, which seems surprising.

**Comment by jeancochrane** [comment]
I think I've gotten to the bottom of this discrepancy! Looks like `scripts/server` was building the `django-q` image implicitly:

https://github.com/azavea/pfb-network-connectivity/blob/ac0bae71429982291c698e39bdf481f9537c5025/scripts/server#L28

However, [`docker-compose up` will only build images if they don't exist](https://stackoverflow.com/questions/39988844/docker-compose-up-vs-docker-compose-up-build-vs-docker-compose-build-no-cach#answer-39988980). Most likely you saw strange behavior because the code had changed to depend on `django_countries`, but the container didn't update accordingly. Because of issues like this one, Ops tends to prefer `docker-compose --build` in our `server` scripts, since it makes sure that the images are always up do date before serving files.

The `cibuild` and `cipublish` scripts don't build images for `django-q` because the Task Definition for the `django-q` Service uses the `pfb-app` image:

https://github.com/azavea/pfb-network-connectivity/blob/ac0bae71429982291c698e39bdf481f9537c5025/deployment/terraform/app.tf#L183

This makes sense in that the `django-q` service is identical to the app service, it just runs a different command. 

Opened up #623 to make that change to `./scripts/update` that you recommended above, as well as introducing the `--build` flag to `docker-compose up` in `./scripts/server`.
