### ISSUE TITLE
Delete San Buenaventura, CA

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#688]
A duplicate of Ventura, CA got created somehow. Please delete San Buenaventura (the first one in the image below).

![image](https://user-images.githubusercontent.com/24727081/52006948-5cfb1380-249b-11e9-82d6-2daf956f6c0a.png)

**Comment by flibbertigibbet** [comment]
Deleted from staging
![image](https://user-images.githubusercontent.com/960264/52007494-8f594080-249c-11e9-9032-8592a8f24a3e.png)

**Comment by KlaasH** [comment]
Not sure why it wasn't coming up in your search.  I searched via the site admin then used the ID of its latest job to get at the neighborhood in a Django shell.
It looks like the "San Buenaventura (Ventura)" one was in the original batch of cities and just-"Ventura" was part of the "200 extra cities" batch run last February.
![image](https://user-images.githubusercontent.com/6598836/52010993-dd724200-24a4-11e9-9381-6e8691b5c4cc.png)

I set the older one to "hidden".  I'm not sure what will happen if we run a new batch that includes "San Buenaventura (Ventura)".  It might reactivate the neighborhood, or it might run an analysis job that never gets seen because it's attached to a "hidden" neighborhood.  In either case, it's worth checking before running the next round of analysis jobs that the batch shapefiles being used don't include it.
