### ISSUE TITLE
Add Minneapolis back

### ISSUE THREAD

**Issue by stephwall** [azavea/pfb-network-connectivity#740]
Made private last year and PFB wants to have back to display on BNA website. It's not listed as a private or public neighborhood in the BNA and giving PFB an error when attempting to upload a new neighborhood boundary with the Minneapolis label.

**Comment by KlaasH** [comment]
It was marked "hidden".  Probably "private" would have been better.  In any case, I updated it manually to "public".  It appears that the analysis for it ran successfully in February, it just couldn't be seen because it was attached to a hidden neighborhood.

![image](https://user-images.githubusercontent.com/6598836/56304041-3b5d1000-610b-11e9-923f-5ce0479faa16.png)
