### ISSUE TITLE
Local analysis setup error: Configuring Docker APT repository fails

### ISSUE THREAD

**Issue by beckymasond** [azavea/pfb-network-connectivity#798]
I'm trying to run the BNA locally to produce results for a number of international cities but the setup process is failing with the error message below. I am trying to run the analysis on the latest "develop" branch. 

![image](https://user-images.githubusercontent.com/13860074/76871773-1a2c0480-6831-11ea-87ef-e98c0a4be810.png)

**Comment by ColeKettler** [comment]
Thanks for reporting this issue, @beckymasond!

I wasn't able to reproduce this issue locally. It's possible that there was a temporary issue with the upstream repository that has since been resolved.

However, the `apt.dockerproject.org` repository is currently [deprecated](https://www.docker.com/blog/changes-dockerproject-org-apt-yum-repositories/). In recognition of that I've introduced changes in #800 that will use the recommended `download.docker.com` APT repository URL.

I suggest pulling the most recent changes to the `develop` branch, running `vagrant destroy`, and then running `./scripts/setup` again to see if the error has been resolved. I hope that these changes improve stability and you do not continue to experience problems running local analysis. If you do, please feel free to reopen this issue and we'll try to resolve it. Thank you again!

**Comment by KlaasH** [comment]
A couple notes on the above:
- To get the `docker` and `docker-compose` version changes, you'll need to copy the new version of `deployment/ansible/group_vars/all.example` to replace your `deployment/ansible/group_vars/all` file.
- Running `vagrant destroy` will delete your development database, so if you have neighborhoods or analysis results in there that you like, you might want to try just re-running `scripts/setup` first to see if the issue is resolved.

**Comment by beckymasond** [comment]
The analysis is running as expected now. Thank you!
